In [10]:
import numpy as np 

A=np.loadtxt(r"C:\Users\51770\Desktop\pythonModeling\11.txt")

x=A[:,0:-1]
y=A[:,-1:]

ones=np.ones(x.shape[0])
X=np.c_[ones,x]
a=np.linalg.inv(X.T@X)@(X.T@y)
print(a)

[[0.05348389]
 [0.38864378]]


In [11]:
yHat=X@a
err=abs(y-yHat)/y*100
print(err)

[[56.73249793]
 [ 9.29595567]
 [12.89326335]
 [19.674251  ]
 [24.76337891]
 [12.02333172]
 [11.26366938]
 [16.57509207]
 [31.9879785 ]
 [12.29507713]
 [ 6.6973136 ]
 [13.58519874]]


In [15]:
from regression import MLR
mlr=MLR(x,y)
mlr.fit()
yHat=mlr.predict(x)

print(mlr.a)
err=abs(yHat-y)/y*100
print(err)

[[0.05348389]
 [0.38864378]]
[[56.73249793]
 [ 9.29595567]
 [12.89326335]
 [19.674251  ]
 [24.76337891]
 [12.02333172]
 [11.26366938]
 [16.57509207]
 [31.9879785 ]
 [12.29507713]
 [ 6.6973136 ]
 [13.58519874]]
