In [2]:
import numpy as np 

A=np.loadtxt(r"C:\Users\51770\Desktop\pythonModeling\11.txt")

x=A[:,0:-1]
y=A[:,1:]

ones=np.ones(x.shape[0])
X=np.c_[ones,x]
a=np.linalg.inv(X.T@X)@(X.T@y)
print(a)

[[0.00772217]
 [0.40264996]]


In [3]:
yHat=X@a
err=abs(y-yHat)/y*100
print(err)

[[ 3.73602474]
 [ 2.07097503]
 [21.47218189]
 [ 5.08807461]
 [26.64157345]
 [ 0.49002419]
 [ 0.38734301]
 [ 0.3261194 ]
 [ 3.61761941]
 [ 0.98950381]
 [ 1.20173753]
 [ 0.41186013]]


In [4]:
from REG import MLR
mlr=MLR(x,y)
mlr.fit()

yHat=mlr.predict(x)
print(mlr.a)

[[0.00772217]
 [0.40264996]]


In [5]:
err=abs(yHat-y)/y*100
print(err)

[[ 3.73602474]
 [ 2.07097503]
 [21.47218189]
 [ 5.08807461]
 [26.64157345]
 [ 0.49002419]
 [ 0.38734301]
 [ 0.3261194 ]
 [ 3.61761941]
 [ 0.98950381]
 [ 1.20173753]
 [ 0.41186013]]


In [5]:
print(mlr.FTest(0.01))

(13114.905640540113, 10.04428927339659, True)


In [7]:
print(mlr.RTest(0.01))

TypeError: 'numpy.ndarray' object is not callable